### ISSUE TITLE
Exercise 8

### ISSUE THREAD

**Issue by jarav** [autotelicum/Smooth-CoffeeScript#13]
Even after editing and entering the correct solution for the 'intensify' function, the tests continue to fail. I think the edited code is not being read by the program that is running the interactive environment.

**Comment by autotelicum** [comment]
Oh, that is not how it is supposed to be. Perhaps there is a bug that I have overlooked or an issue with the browser/editor combination that you are using. Could you tell me which browser, OS and version you are using and which settings did you choose i.e. plain text or CodeMirror editor and auto or manual evaluate. I would like to try your combination, so I can reconstruct the issue.

Maybe not the issue here but one way for it to happen is to choose 'manual' evaluation up in the top menu (where you then have to press `shift/enter` to get code evaluated). Then type in a solution _without_ pressing `shift/enter` and clicking on the `run` button. Since the entered code was not evaluated the old version (`intensify = (n) -> 2`) is still defined and used in the test.

**Comment by jarav** [comment]
Sorry. You were right. It was set to manual evaluation and I had not pressed 'shift' + 'enter'. I am trying this out on Google-Chrome on Linux.
