### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by l0b0** [autotelicum/Smooth-CoffeeScript#17]
What is the exact command used for compiling the LyX files into PDF? It might be useful to put it in a Makefile to be able to quickly validate changes.

**Comment by autotelicum** [comment]
I don't have my laptop, so i'll get back to this in detail later I'm writing on my 3ds actually. The process is selecting with/without solutions and then running pdf/xetex from file/export.

**Comment by autotelicum** [comment]
Activate one branch and deactivate the other (choosing with or without solutions) in Document Settings / Branches (or right-click the two branch sections at the top of the LyX file). Normally I leave this unchanged so solutions are included in drafts and only switch the setting once everything is done to additionally produce a version without solutions.

To generate a draft PDF, select `View [PDF (XeTeX)]` or `Update [PDF (XeTeX)]` in the View menu. There are icons in the toolbar and keyboard shortcuts for it. It should then open your PDF viewer. To produce the final PDF versions, select `Export PDF (XeTeX)` in the File menu and rename the file. Then activate the other branch and export again.

LyX does have a command line interface, maybe the -e and -x options can be used to do the same. I have never tried it. I have found that clicking on `update` in the toolbar or `export` in the menu was adequate.

---

Now all of this requires a TeX installation with lots of packages - I guess a full install of TeX (1.6Gb download) should do it. But I have a low bandwidth connection, so I install basic (80Mb download or something like that) and then try viewing a file, which will fail with some missing package, locate the package in the `TeX Live Utility` and try again ... and again ...

The reason to use XeTeX has to do with native fonts. In the Document Settings / Fonts I enabled `Use non-TeX fonts` and Base Size 12. Setting Roman to Times, Sans Serif to Arcitectura (an old freeware font used for the headlines) at 94% and Typewriter to Consolas at 96%. The formatting was chosen specifically for those fonts to keep kerning and line break issues to a minimum. Formatting the document still took about a week of spare time. You can use different fonts, but at least the Roman font has to include some Unicode characters like pi (as far as I recall) and preferably ligatures.

---

So generating the PDF is basically one-click in the toolbar or menu. Setting up TeX and fonts is the issue. A make file does not make that easier. So does that answer your question?

**Comment by autotelicum** [comment]
Oh yeah, there is also the somewhat Kindle compatible [HTML version](http://autotelicum.github.com/Smooth-CoffeeScript/SmoothCoffeeScript.html) I created upon [request](https://github.com/autotelicum/Smooth-CoffeeScript/issues/6) because the Kindle could not display PDF very well. That was done with [elyxer](http://elyxer.nongnu.org/) 1.2.3. It was the first tool that didn't just crash on the book, but the result was still not that good, so I spent a couple of days manually fixing the HTML.

That means that any changes in the LyX file has to be manually brought over into that version - in addition to bringing changes over into the pandoc markdown for the interactive HTML5 version (that the Kindle can not handle either).

Obviously the tools are not ideal for maintenance. It could probably have been done better if I had had previous experience with producing e-books. But as CoffeeScript is now stable and the book has been out for almost a year I don't expect too many changes, just additions that I can copy/paste as the language evolves. So I don't think attempting to create a makefile is worth it, but we can reopen the issue if you want to try to do it.
