### ISSUE TITLE
awkward paragraph

### ISSUE THREAD

**Issue by aeosynth** [autotelicum/Smooth-CoffeeScript#3]
1.2, page 20

> Calculations with whole numbers (also called integers) that fit in 52 bits are guaranteed to always be precise. Unfortunately, calculations with fractional numbers are generally not. Like (pi) can not be precisely expressed by a finite amount of decimal digits, many numbers lose some precision when only 64 bits are available to store them.

http://en.wikipedia.org/wiki/Whole_number

> **Whole number** is a term with inconsistent definitions by different authors

the 'generally' is redundant - calculations are not _guaranteed_ to work, full stop.

the last sentence is just awkward.

you jump between 52 bits, 64 bits, and, in the footnote, 53 bits. kind of confusing.

here's my rewrite:

> Calculations with numbers expressible in 64 bits are guaranteed to always be precise. Unfortunately, some numbers, such as (pi), can not be precisely expressed in 64 bits, and will lose some precision when stored.

**Comment by aeosynth** [comment]
also, same page:

> Any whole number less than 2^52, which is over 10^15, will safely fit in a CoffeeScript number.

-2^53 is a whole number less than 2^52 which will _not_ fit.

**Comment by autotelicum** [comment]
The background for the not-so-clear description is in the ECMAScript section on numbers. See [Numbers](http://bclary.com/2004/11/07/#a-8.5) or [the latest standard in pdf](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf). I will look into it in the weekend. It is a bit complicated and I need a quiet moment to read that ECMAScript section fully.

Thanks for bringing it up and do let me know if you find something else that might be incorrect.

**Comment by autotelicum** [comment]
I looked into the definition of the Number type in ECMAScript and it seems that the text is correct. I think it is fine if the text makes the reader think: WTF?! because JavaScript numbers and math do come with built-in gotcha's.

I would change the text if this was DrRacket (Scheme) where numbers work as most people would expect them to. The numeric issues shown later in the book would not be present if JavaScript numbers behaved as numbers do in DrRacket. Compare [this](http://docs.racket-lang.org/reference/numbers.html) with the EcmaScript link I gave above.

The EcmaScript definition is precise, yet incredibly hard to understand. In the text 'whole numbers' is a fuzzy term. Like many things in natural language it only gives us an approximate meaning from the context. I think it is ok to use a fuzzy word here - the footnote is there for those who want to look up a precise definition.

About: 'Calculations with numbers expressible in 64 bits are guaranteed to always be precise.'
This number is expressible in 57 bits

```
coffee> bits = (94503599627370496).toString 2
'101001111101111101000010111101101110010010000000000000000'
coffee> bits.length
57
```

Adding something ending in 6 to itself should give something that ends in 2 but:

```
coffee> 94503599627370496 + 94503599627370496
189007199254741000
```

DrRacket and wxMaxima both give the correct result:

```
> (+ 94503599627370496 94503599627370496)
189007199254740992
/* [wxMaxima: input   start ] */
94503599627370496 + 94503599627370496;
/* [wxMaxima: input   end   ] */
(%o1) 189007199254740992
```

I understand why you brought this up as an issue in the text. It would be nice if JavaScript had numbers like DrRacket, much easier to explain and use, but that is not how it is. It was worth investigating.
