### ISSUE TITLE
qc not working properly (chapter 3)

### ISSUE THREAD

**Issue by aetherical** [autotelicum/Smooth-CoffeeScript#7]
CoffeeScript version 1.1.2

I assume this is likely related to the issue with changes between 1.1.1 and 1.1.2 --

I've applied the workaround to get prelude to work (as noted in a different issue).

However, in chapter 3, when I execute qc.test(), I get a:

TypeError: boolean is not a function
at Boolean.CALL_NON_FUNCTION (native)
at (this line depends whether I am invoking it from my script or in repl)
at Prop.body (..../prelude.coffee:196:85)
at Prop.run (..../qc.js:640:38)
at ..../prelude/qc.js:640:38
at Object.runAllProps (..../prelude/qc.js:645:9)
at Object.test (..../prelued/prelude.coffee:201:42)
at [object Context]:2:8
at Object.eval (..../coffee-script/lib/coffee-script.js:114:21)
at Interface.<anonymous> (...../coffee-script/lib/repl.js:44:34)

Unfortunately I'm still learning coffeescript and so do not know enough where to understand the error better.  I am guessing, however, it does seem to have something to do with the workaround, but I could be totally off base.

As a related question, how do I interpret the stacktrace -- is that line number and character; I assume it's from the compiled javascript?

Thanks,
Matt

**Comment by aetherical** [comment]
Oh, I do want to say thank you for all of your hard work!!!  I really appreciate it.

**Comment by autotelicum** [comment]
I'm sorry. This slipped my attention. I was going to respond when Issue #5 - also related to the REPL in 1.1.2 - was resolved, but that ended up waiting for https://github.com/jashkenas/coffee-script/issues/1654 and https://github.com/jashkenas/coffee-script/pull/1661 longer than I had expected... until https://github.com/joyent/node/pull/1904 settled it.

I haven't reproduced this problem, because the CoffeeScript configuration I have is based on unstable node.js and a patched CoffeeScript. I will retest this (and everything else) when node.js 0.6 (expected next week) and hopefully soon after an updated CoffeeScript - that should resolve the REPL issues - is released.

The line numbers in the stack trace refers to the JavaScript intermediary, so if it is not immediately clear what a trace refers to, then compiling the CoffeeScript with `coffee -c` can give a JavaScript version of the file.

Again, sorry about the slip and thank you for reporting this.

**Comment by autotelicum** [comment]
Handled by update to CoffeeScript 1.1.3
