### ISSUE TITLE
Accessing array keys/properties

### ISSUE THREAD

**Issue by singlow** [autotelicum/Smooth-CoffeeScript#9]
When you mentioned (under Data Structures) that using dot property syntax for arrays/objects, you mentioned several criteria for when it may be used or not used. However you should mention that you cannot use dot syntax for properties whose names are reserved words. You did say they must be valid variable names, but most beginners will not make that connection. I encountered recently a tough to find bug where the property someObject.new was being referenced and several browsers choked, while others did not.

**Comment by autotelicum** [comment]
I don't mention it because on the [coffeescript.org literals below the first example under Objects and Arrays](http://jashkenas.github.com/coffee-script/#literals) page it says: "In JavaScript, you can't use reserved words, like class, as properties of an object, without quoting them as strings. CoffeeScript notices reserved words used as keys in objects and quotes them for you, so you don't have to worry about it (say, when using jQuery)."

I haven't tested that this is really the case. If it is not then it should possibly be reported to the CoffeeScript project. Is it an exception to this that you have found or were your experience based on JavaScript? It is a subtle change.

In the book it is mentioned just before Exercise 4 (p36) that: "[Reserved words] are also officially not allowed to be used as variable names, though some environments do allow them. The full list in Reserved Words is rather long.
Do not worry about memorising these for now, but remember that this might be the problem when something does not work as expected. In my experience, char (to store a one-character string) and class are the most common names to accidentally use."

**Comment by singlow** [comment]
Hmm. You are right. I tested and coffeescript is quoting them for me. Not
sure how that was not happening when I had this issue.

On Mon, Nov 21, 2011 at 10:30 AM, autotelicum <
reply@reply.github.com

**Comment by autotelicum** [comment]
That's fine then. Do get in touch if there are other things that strike you as odd.

I think discussing it too much in the book would likely confuse more than help. When beginning, it is best to avoid reserved words altogether - and that is mentioned earlier in Basic CoffeeScript. Where the special CoffeeScript feature can be helpful - in my view - is when making DSL's but that's an advanced technique beyond the book.

I'll close this one.
